### ISSUE TITLE
Active cooler is not accessible

### ISSUE THREAD

**Issue by krin-san** [cyb0124/FissionOpt#2]
Somehow an active cooler was placed in non-accessible position with no way to pipe fluids to it from inside.
![short_resule](https://user-images.githubusercontent.com/2318002/89343396-81ddd180-d6a4-11ea-96d8-7fd466552623.png)

S1 Size: 7x7x7
S2 Fuel: HECm-243 @ Default config
S4 Rates configured according to [DD&SS modpack config](https://github.com/cyb0124/FissionOpt/files/5024433/nuclearcraft.txt) where passive cooler Qz = 90 and all active coolers has 2x default rates
S5 Default parameters

I run generator with this config and left (forgot) for some time, stopping it on episode 819.
[Full page capture](https://user-images.githubusercontent.com/2318002/89343222-417e5380-d6a4-11ea-97a5-4689fea648e8.png)

**Comment by cyb0124** [comment]
Hi, you can pump it through a buffer in the bottom face of the reactor into Layer 1. Then it will flow into Layer 2 since the two coolers are adjacent to each other.

**Comment by krin-san** [comment]
Didn't aware of this feature and it's not mentioned in on wiki pages. I also tried to setup it like that, with 2 active coolers one above the other, buffer on top and water piping in: top cooler gets filled but not the bottom one.

Was this feature introduced after version 2.18r ?

**Comment by cyb0124** [comment]
This feature was introduced in 2.8, which is two and a half years ago. Could you post a screenshot of how you tested it?

**Comment by cyb0124** [comment]
Is the "Passive Permeation" option in "Processor Configs" on?

Regarding the cooling rate, the numbers in the config are in the unit of H/mB, not H/t. You need to multiply that by the consumption rate (default is 10mB/s=0.5mB/t) to get H/t.

**Comment by krin-san** [comment]
Nope, it's set to `false`. That's not a default value, probably was changed by modpack author. And that was not even changed to balance increased cooling rates, because cooling rates and consumption rates are default (didn't noticed that before).

Thank you for the explanation! It helps me a lot to understand how things works =]
