### ISSUE TITLE
how do you know whe its done?

### ISSUE THREAD

**Issue by mpg0907** [cyb0124/FissionOpt#3]
i have run the program but I dont know when it is doen cous it keep going with the episode, stages and iteration?

**Comment by cyb0124** [comment]
It doesn't have an end. As long as it is running, it will try keep improving the design but the improvment diminishes over time. Generally, 10 episodes give you an average usable design; 100 episodes give you a pretty good design; 1000 episodes squeeze out that last 1% performance.

**Comment by mpg0907** [comment]
thank you.
