### ISSUE TITLE
Any information on how much progress has been made?

### ISSUE THREAD

**Issue by vvanhee** [cyb0124/FissionOpt#9]
My 5x7x5 generator had been running for hours, so I limited it to just a few cooler types but I have no idea how close it is to reaching a solution... How do I interpret the bar graph? Is there any way of knowing how many minutes / hours / decades the thing is going to run? What are some general expectations regarding compute time for various configurations? Any way of at least getting a suboptimal solution faster?

Thanks!

**Comment by GiacomoAru** [comment]
i don't think the algorithm will stop ever, when you like the configuration you reach you can stop the reserarch. more you go more time you need to find a better configuaration, if it's possible. The graph seems to show the progress, nothing you need to understand for use the tool, probably :)

my english is very bad but try to understand much you can, bye

**Comment by vvanhee** [comment]
Thanks, I feel like the reactor I was making didn't ever update after the first one displayed, so I was confused. I guess that was the best one. Thanks very much
